openapi: 3.2.0
info:
  description: BankID Relying Party API v6.0
  license:
    name: BankID Privacy policy
    url: https://www.bankid.com/en/integritetspolicy
  title: Relying Party Phone API
  version: 6.1.11
servers:
- description: Test server
  url: https://appapi2.test.bankid.com/rp/v6.0
- description: Production server
  url: https://appapi2.bankid.com/rp/v6.0
tags:
- name: Phone
paths:
  /phone/auth:
    post:
      description: 'Initiates an identification order when the user is talking to your organization over the phone.


        Use the `/collect` method to query the status of the order.'
      operationId: phoneAuth
      requestBody:
        content:
          application/json:
            examples:
              fromUser:
                summary: Phone request where the user called you
                value:
                  callInitiator: user
                  userVisibleData: IyBFeGFtcGxlClRoaXMgaXMgYW4gKmV4YW1wbGUqIHRleHQ=
                  userVisibleDataFormat: simpleMarkdownV1
                  personalNumber: '192110101414'
              fromRP:
                summary: Phone request where you called the user
                value:
                  callInitiator: RP
                  userVisibleData: IyBFeGFtcGxlClRoaXMgaXMgYW4gKmV4YW1wbGUqIHRleHQ=
                  userVisibleDataFormat: simpleMarkdownV1
                  personalNumber: '192110101414'
              stepUp:
                summary: Require the user to perform a step up by either verifying ID document or using facial recognition
                value:
                  callInitiator: user
                  personalNumber: '200001012384'
                  requirement:
                    stepUp:
                    - mrtd
                    - face
            schema:
              $ref: '#/components/schemas/phoneAuth_request'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/limited_response'
          description: Request successful.
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_response'
          description: Bad request.
        '401':
          description: You do not have access to the service.
        '403':
          description: You do not have access to the service.
        '404':
          description: An invalid URL path was used.
        '405':
          description: Only HTTP method POST is allowed.
        '408':
          description: Timeout while transmitting the request.
        '415':
          description: The type is missing or invalid.
        '500':
          description: Internal technical error in the BankID system.
        '503':
          description: The service is temporarily unavailable.
      summary: Create an identification order for a phone call
      tags:
      - Phone
  /phone/sign:
    post:
      description: 'Initiates a signature order when the user is talking to your organization-over the phone.


        Use the `/collect` method to query the status of the order.'
      operationId: phoneSign
      requestBody:
        content:
          application/json:
            examples:
              fromUser:
                summary: Phone request where the user called you
                value:
                  callInitiator: user
                  userVisibleData: IyBFeGFtcGxlClRoaXMgaXMgYW4gKmV4YW1wbGUqIHRleHQ=
                  userVisibleDataFormat: simpleMarkdownV1
                  personalNumber: '192110101414'
              fromRP:
                summary: Phone request where you called the user
                value:
                  callInitiator: RP
                  userVisibleData: IyBFeGFtcGxlClRoaXMgaXMgYW4gKmV4YW1wbGUqIHRleHQ=
                  userVisibleDataFormat: simpleMarkdownV1
                  personalNumber: '192110101414'
              stepUp:
                summary: Require the user to perform a step up by either verifying ID document or using facial recognition
                value:
                  callInitiator: RP
                  userVisibleData: I0V4YW1wbGUKVGhpcyBpcyBhbiAqZXhhbXBsZSogdGV4dA==
                  personalNumber: '200001012384'
                  requirement:
                    stepUp:
                    - mrtd
                    - face
            schema:
              $ref: '#/components/schemas/phoneSign_request'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/limited_response'
          description: Request successful.
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_response'
          description: Bad request.
        '401':
          description: You do not have access to the service.
        '403':
          description: You do not have access to the service.
        '404':
          description: An invalid URL path was used.
        '405':
          description: Only HTTP method POST is allowed.
        '408':
          description: Timeout while transmitting the request.
        '415':
          description: The type is missing or invalid.
        '500':
          description: Internal technical error in the BankID system.
        '503':
          description: The service is temporarily unavailable.
      summary: Create a signature order for a phone call
      tags:
      - Phone
  /phone/payment:
    post:
      description: 'Initiates a payment order when the user is talking to your organization-over the phone.


        Use the `/collect` method to query the status of the order.'
      operationId: phonePayment
      requestBody:
        content:
          application/json:
            examples:
              fromUser:
                summary: Phone request where the user initiated the call
                value:
                  personalNumber: '200001012384'
                  callInitiator: user
                  userVisibleData: IyBFeGFtcGxlClRoaXMgaXMgYW4gKmV4YW1wbGUqIHRleHQ=
                  userVisibleDataFormat: simpleMarkdownV1
                  userVisibleTransaction:
                    transactionType: direct
                    recipient:
                      nameB64: UGF5bWVudCBSZWNpcGllbnRzIEluYy4=
                      accountNumber: '8862321312'
                    money:
                      amount: 9900,01
                      currency: USD
                    thirdPartyInitiatorB64: VGhpcmRQYXJ0eSBDb21wYW55
              fromRP:
                summary: Phone request where the service initiated the call
                value:
                  personalNumber: '200001012384'
                  callInitiator: RP
                  userVisibleData: IyBFeGFtcGxlClRoaXMgaXMgYW4gKmV4YW1wbGUqIHRleHQ=
                  userVisibleDataFormat: simpleMarkdownV1
                  userVisibleTransaction:
                    transactionType: direct
                    recipient:
                      nameB64: UGF5bWVudCBSZWNpcGllbnRzIEluYy4=
                      accountNumber: '8862321312'
                    money:
                      amount: 9900,01
                      currency: USD
                    thirdPartyInitiatorB64: VGhpcmRQYXJ0eSBDb21wYW55
            schema:
              $ref: '#/components/schemas/phonePayment_request'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/limited_response'
          description: Request successful.
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_response'
          description: Bad request.
        '401':
          description: You do not have access to the service.
        '403':
          description: You do not have access to the service.
        '404':
          description: An invalid URL path was used.
        '405':
          description: Only HTTP method POST is allowed.
        '408':
          description: Timeout while transmitting the request.
        '415':
          description: The type is missing or invalid.
        '500':
          description: Internal technical error in the BankID system.
        '503':
          description: The service is temporarily unavailable.
      summary: Create a payment order for a phone call
      tags:
      - Phone
  /phone/payment/bulk:
    post:
      description: 'Initiates a bulk payment order when the user is talking to your organization-over the phone.


        Use the `/collect` method to query the status of the order.'
      operationId: phonePaymentBulk
      requestBody:
        content:
          application/json:
            examples:
              fromUser:
                summary: Phone request where the user called you
                value:
                  personalNumber: '190010101010'
                  callInitiator: user
                  userVisibleData: IyBFeGFtcGxlClRoaXMgaXMgYW4gKmV4YW1wbGUqIHRleHQ=
                  userVisibleTransactionBulk:
                    payments:
                    - transactionType: plusgiro
                      recipient:
                        accountNumber: 1234-1234
                        nameB64: UGF5bWVudCBSZWNpcGllbnRzIEluYy4=
                      money:
                        amount: 100,00
                        currency: EUR
                      riskWarning: largeAmount
                      date: 2025-11-10
                    - transactionType: bankgiro
                      recipient:
                        nameB64: UGF5bWVudCBSZWNpcGllbnRzIEJhbmtnaXJvIEluYy4=
                        accountNumber: 1234-1234
                      money:
                        amount: 100,00
                        currency: SEK
                      riskWarning: largeAmount
                      date: 2025-11-10
                    sums:
                    - amount: 100,00
                      currency: EUR
              fromRP:
                summary: Phone request where you called the user
                value:
                  personalNumber: '190010101010'
                  callInitiator: RP
                  userVisibleData: IyBFeGFtcGxlClRoaXMgaXMgYW4gKmV4YW1wbGUqIHRleHQ=
                  userVisibleTransactionBulk:
                    payments:
                    - transactionType: plusgiro
                      recipient:
                        accountNumber: 1234-1234
                        nameB64: UGF5bWVudCBSZWNpcGllbnRzIEluYy4=
                      money:
                        amount: 100,00
                        currency: EUR
                      riskWarning: largeAmount
                      date: 2025-11-29
                    - transactionType: bankgiro
                      recipient:
                        nameB64: UGF5bWVudCBSZWNpcGllbnRzIEJhbmtnaXJvIEluYy4=
                        accountNumber: 1234-1234
                      money:
                        amount: 100,00
                        currency: EUR
                      riskWarning: largeAmount
                      date: 2025-11-10
                    sums:
                    - amount: 200,00
                      currency: EUR
            schema:
              $ref: '#/components/schemas/phonePaymentBulk_request'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/limited_response'
          description: Request successful.
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_response'
          description: Bad request.
        '401':
          description: You do not have access to the service.
        '403':
          description: You do not have access to the service.
        '404':
          description: An invalid URL path was used.
        '405':
          description: Only HTTP method POST is allowed.
        '408':
          description: Timeout while transmitting the request.
        '415':
          description: The type is missing or invalid.
        '500':
          description: Internal technical error in the BankID system.
        '503':
          description: The service is temporarily unavailable.
      summary: Create a bulk payment order for a phone call
      tags:
      - Phone
components:
  schemas:
    RecipientCard:
      allOf:
      - $ref: '#/components/schemas/RecipientCommon'
      - properties:
          name:
            description: 'The name of the recipient of the payment.


              For the transaction type `"card"`, this is the merchant name.

              This property is here for backwards compatibility only.

              The preferred way of declaring the name of the recipient is to use nameB64 instead.'
            maxLength: 40
            type: string
        type: object
      description: 'Displayed name for the recipient of the payment.

        Exactly one of `name` and `nameB64` must be populated.'
      title: recipientCard
    UserVisibleTransactionParentType:
      properties:
        transactionType:
          description: 'The type of transaction.


            The possible values have the following meaning:


            - `card`: Card payment.

            - `npa`: Non-payment authentication.

            - `bankgiro`: Bankgiro payment.

            - `plusgiro`: Plusgiro payment.

            - `samebank`: Same bank transfer.

            - `domesticbank`: Domestic bank transfer.

            - `foreignbank`: Foreign bank transfer.

            - `direct`: Direct payment.'
          enum:
          - card
          - npa
          - bankgiro
          - plusgiro
          - samebank
          - domesticbank
          - foreignbank
          - direct
          type: string
        date:
          description: 'The date for the payment to occur.


            Should be a formatted as YYYY-MM-DD.'
          format: date
          type: string
        riskWarning:
          $ref: '#/components/schemas/riskWarning'
        recurring:
          default: false
          description: Indicate to the user if the payment is a recurring one or not.
          type: boolean
        thirdPartyInitiatorB64:
          description: 'The third party initiating the payment.


            Should be a base64 encoded utf-8 string with a maximum length of 40 unicode code points.'
          maxLength: 270
          minLength: 1
          type: string
      type: object
    Npa:
      allOf:
      - $ref: '#/components/schemas/UserVisibleTransactionParentType'
      - properties:
          recipient:
            $ref: '#/components/schemas/RecipientNpa'
      required:
      - recipient
      title: npa
      type: object
    callInitiator:
      description: 'Indicates if the user or your organization initiated the phone call.


        The possible values have the following meaning:


        *  `user`: The user called your organization.

        *  `RP`: Your organization called the user.'
      enum:
      - user
      - RP
      example: user
      type: string
    cardReader:
      description: "Whether the user needs to complete the order using a card reader for the signature.\n\nThe possible values have the following meaning:\n\n  *  `class1`: The order must be confirmed with a card reader where the PIN code is entered on a computer keyboard,\n     or a card reader of higher class.\n  *  `class2`: The order must be confirmed with a card reader where the PIN code is entered on the reader.\n\nThis condition should always be combined with a `certificatePolicies` for a smart card to avoid undefined\nbehaviour.\n\nNo card reader is required by default."
      enum:
      - class1
      - class2
      type: string
    RecipientNpa:
      allOf:
      - $ref: '#/components/schemas/RecipientCommon'
      - properties:
          name:
            description: 'The name of the recipient of the payment.

              This property is here for backwards compatibility only.

              The preferred way of declaring the name of the recipient is to use nameB64 instead.'
            maxLength: 40
            type: string
        type: object
      description: 'Displayed name for the recipient of the payment.

        Exactly one of `name` and `nameB64` must be populated.'
      title: recipientNpa
    phoneAuth_request:
      properties:
        callInitiator:
          $ref: '#/components/schemas/callInitiator'
        personalNumber:
          description: 'The ID number of the user.


            The ID number is a Swedish national identification number (12 digits).'
          example: '200001012384'
          maxLength: 12
          minLength: 12
          pattern: ^[0-9]*$
          type: string
        userNonVisibleData:
          description: 'Data that you wish to include but not display to the user.


            The value must be base 64-encoded.'
          example: VGV4dCBpbmNsdWRlZCBidXQgbm90IGRpc3BsYXllZCB0byB0aGUgdXNlcg==
          maxLength: 1500
          minLength: 1
          type: string
        userVisibleData:
          description: 'Text displayed to the user during the order.


            The purpose is to provide context, thereby enabling the user to detect identification errors and avert fraud

            attempts.


            The text can be formatted using CR, LF and CRLF for new lines. The text must be encoded as UTF-8 and then base 64

            encoded.'
          example: VGhpcyBpcyBhIHNhbXBsZSB0ZXh0Cg==
          maxLength: 1500
          minLength: 1
          type: string
        userVisibleDataFormat:
          $ref: '#/components/schemas/userVisibleDataFormat'
        requirement:
          $ref: '#/components/schemas/phoneAuth_request_requirement'
      required:
      - callInitiator
      - personalNumber
      type: object
    userVisibleDataFormat:
      description: "If present and set to `\"simpleMarkdownV1\"`, this parameter indicates that `userVisibleData` holds formatting\ncharacters.\n\nThe possible values have the following meaning:\n\n-  `plaintext`: `userVisibleData` contains base 64 encoded text using a sub-set of UTF-8 and CR, LF or CRLF for\n   line breaks..\n-  `simpleMarkdownV1`: `userVisibleData` contains Simple Markdown version 1.\n\nPlease see\n[the documentation](https://developers.bankid.com/getting-started/backend/formatting-text/syntax-special-characters-and-rendering)\nfor more information about the format."
      enum:
      - plaintext
      - simpleMarkdownV1
      type: string
    ForeignBank:
      allOf:
      - $ref: '#/components/schemas/UserVisibleTransactionParentType'
      - properties:
          money:
            $ref: '#/components/schemas/Money'
          recipient:
            $ref: '#/components/schemas/RecipientForeignBank'
      required:
      - date
      - money
      - recipient
      title: foreignbank
      type: object
    RecipientForeignBank:
      allOf:
      - $ref: '#/components/schemas/RecipientCommon'
      - properties:
          accountNumber:
            description: The account number of the recipient of the payment.
            maxLength: 42
            minLength: 1
            pattern: ^[A-Z0-9.,() -]+$
            type: string
        type: object
      description: Displayed name and account number for the recipient of the payment.
      required:
      - accountNumber
      title: recipientForeignBank
    SameBank:
      allOf:
      - $ref: '#/components/schemas/UserVisibleTransactionParentType'
      - properties:
          money:
            $ref: '#/components/schemas/Money'
          recipient:
            $ref: '#/components/schemas/RecipientSameBank'
      required:
      - date
      - money
      - recipient
      title: samebank
      type: object
    DomesticBank:
      allOf:
      - $ref: '#/components/schemas/UserVisibleTransactionParentType'
      - properties:
          money:
            $ref: '#/components/schemas/Money'
          recipient:
            $ref: '#/components/schemas/RecipientDomesticBank'
      required:
      - date
      - money
      - recipient
      title: domesticbank
      type: object
    Plusgiro:
      allOf:
      - $ref: '#/components/schemas/UserVisibleTransactionParentType'
      - properties:
          money:
            $ref: '#/components/schemas/Money'
          recipient:
            $ref: '#/components/schemas/RecipientPlusgiro'
      required:
      - date
      - money
      - recipient
      title: plusgiro
      type: object
    UserVisibleTransaction:
      description: Information about the transaction being approved.
      discriminator:
        mapping:
          card: '#/components/schemas/Card'
          npa: '#/components/schemas/Npa'
          bankgiro: '#/components/schemas/Bankgiro'
          plusgiro: '#/components/schemas/Plusgiro'
          samebank: '#/components/schemas/SameBank'
          domesticbank: '#/components/schemas/DomesticBank'
          foreignbank: '#/components/schemas/ForeignBank'
          direct: '#/components/schemas/Direct'
        propertyName: transactionType
      oneOf:
      - $ref: '#/components/schemas/Card'
      - $ref: '#/components/schemas/Npa'
      - $ref: '#/components/schemas/Bankgiro'
      - $ref: '#/components/schemas/Plusgiro'
      - $ref: '#/components/schemas/SameBank'
      - $ref: '#/components/schemas/DomesticBank'
      - $ref: '#/components/schemas/ForeignBank'
      - $ref: '#/components/schemas/Direct'
      required:
      - transactionType
      type: object
    phoneAuth_request_requirement:
      description: Requirements on how the authentication order must be performed.
      properties:
        cardReader:
          $ref: '#/components/schemas/cardReader'
        certificatePolicies:
          description: 'The OID in certificate policies in the user certificate.


            One wildcard is allowed from position 5 and forward (`"1.2.752.78.*"`).


            Available values for production BankIDs are:

            *  `"1.2.752.78.1.1"` - BankID on file

            *  `"1.2.752.78.1.2"` - BankID on card

            *  `"1.2.752.78.1.5"` - Mobile BankID


            Available values for test BankIDs are:

            *  `"1.2.3.4.5"` - BankID on file

            *  `"1.2.3.4.10"` - BankID on card

            *  `"1.2.3.4.25"` - Mobile BankID

            *  `"1.2.752.60.1.6"` - Test BankID for some BankID banks


            When using one of the _BankID on card_ policies, the `cardReader` requirement can be used to further restrict the

            type of card reader allowed. If no `cardReader` requirement is passed, all supported kinds of card readers are

            permitted.'
          example:
          - 1.2.752.78.1.1
          items:
            type: string
          type: array
        mrtd:
          description: 'Whether the user needs to confirm their identity with a valid Swedish passport or national ID card to complete the

            order.


            No identity confirmation is required by default.'
          type: boolean
        pinCode:
          description: Users are required to confirm the order with their security code even if they have biometrics activated.
          example: false
          type: boolean
        stepUp:
          description: 'Whether the user needs to perform a step up.


            The possible values have the following meaning:

            - `mrtd`: Confirm identity with a valid Swedish passport or national ID card to complete the order.

            - `face`: Confirm identity with facial recognition.


            Use multiple values to let the user choose between the available identity confirmations.


            The `requirement.stepUp` property can not be used in combination with the property `requirement.mrtd`.


            Requesting identity confirmation with facial recognition as the only option is not supported.


            No identity confirmation is required by default.'
          items:
            type: string
          type: array
      type: object
    UserVisibleTransactionBulk_payments_inner_allOf_fromAccount:
      description: "The account the payment is taken from.\n\nItems adjacent to each other in `payments` will be grouped together if share the same `fromAccount` values.  \n\nEither `nameB64` or `accountNumber` is required."
      properties:
        nameB64:
          description: 'The name of the account.


            Should be a base64 encoded utf-8 string with a maximum length of 40 unicode code points.'
          maxLength: 215
          minLength: 1
          type: string
        accountNumber:
          description: The account number the transfer is sourced from.
          format: string
          maxLength: 42
          minLength: 1
          pattern: ^[A-Z0-9.,() -]+$
          type: string
      type: object
    TransactionBulk:
      properties:
        transactionType:
          description: 'The type of transaction.


            The possible values have the following meaning:


            - `bankgiro`: Bankgiro payment.

            - `plusgiro`: Plusgiro payment.

            - `samebank`: Same bank transfer.

            - `domesticbank`: Domestic bank transfer.

            - `foreignbank`: Foreign bank transfer.'
          enum:
          - bankgiro
          - plusgiro
          - samebank
          - domesticbank
          - foreignbank
          type: string
        date:
          description: 'The date for the payment to occur.


            Should be a formatted as YYYY-MM-DD.'
          format: date
          type: string
        riskWarning:
          $ref: '#/components/schemas/riskWarning'
      required:
      - date
      - money
      - transactionType
      type: object
    UserVisibleTransactionBulk_payments_inner:
      allOf:
      - $ref: '#/components/schemas/TransactionBulk'
      - properties:
          money:
            $ref: '#/components/schemas/Money'
          recipient:
            $ref: '#/components/schemas/RecipientGenericBulk'
          fromAccount:
            $ref: '#/components/schemas/UserVisibleTransactionBulk_payments_inner_allOf_fromAccount'
          riskFlags:
            $ref: '#/components/schemas/riskFlags'
      required:
      - recipient
    RecipientGenericBulk:
      allOf:
      - $ref: '#/components/schemas/RecipientCommon'
      - properties:
          accountNumber:
            description: The account number of the recipient of the payment.
            maxLength: 42
            minLength: 1
            pattern: ^[A-Z0-9.,() -]+$
            type: string
        type: object
      description: Displayed name and account number for the recipient of the payment.
      required:
      - accountNumber
    phoneSign_request_requirement:
      description: Requirements on how the signature order must be performed.
      properties:
        cardReader:
          $ref: '#/components/schemas/cardReader'
        certificatePolicies:
          description: 'The OID in certificate policies in the user certificate.


            One wildcard is allowed from position 5 and forward (`"1.2.752.78.*"`).


            Available values for production BankIDs are:

            *  `"1.2.752.78.1.1"` - BankID on file

            *  `"1.2.752.78.1.2"` - BankID on card

            *  `"1.2.752.78.1.5"` - Mobile BankID


            Available values for test BankIDs are:

            *  `"1.2.3.4.5"` - BankID on file

            *  `"1.2.3.4.10"` - BankID on card

            *  `"1.2.3.4.25"` - Mobile BankID

            *  `"1.2.752.60.1.6"` - Test BankID for some BankID banks


            When using one of the _BankID on card_ policies, the `cardReader` requirement can be used to further restrict the

            type of card reader allowed. If no `cardReader` requirement is passed, all supported kinds of card readers are

            permitted.'
          example:
          - 1.2.752.78.1.1
          items:
            type: string
          type: array
        mrtd:
          description: 'Whether the user needs to confirm their identity with a valid Swedish passport or national ID card to complete the

            order.


            No identity confirmation is required by default.'
          type: boolean
        pinCode:
          description: Users are required to confirm the order with their security code even if they have biometrics activated.
          example: false
          type: boolean
        stepUp:
          description: 'Whether the user needs to perform a step up.


            The possible values have the following meaning:

            - `mrtd`: Confirm identity with a valid Swedish passport or national ID card to complete the order.

            - `face`: Confirm identity with facial recognition.


            Use multiple values to let the user choose between the available identity confirmations.


            The `requirement.stepUp` property can not be used in combination with the property `requirement.mrtd`.


            Requesting identity confirmation with facial recognition as the only option is not supported.


            No identity confirmation is required by default.'
          items:
            type: string
          type: array
      type: object
    RecipientBankgiro:
      allOf:
      - $ref: '#/components/schemas/RecipientCommon'
      - properties:
          accountNumber:
            description: The account number of the recipient of the payment.
            maxLength: 42
            minLength: 1
            pattern: ^[A-Z0-9.,() -]+$
            type: string
        type: object
      description: Displayed name and account number for the recipient of the payment.
      required:
      - accountNumber
      title: recipientBankgiro
    phonePayment_request:
      properties:
        callInitiator:
          $ref: '#/components/schemas/callInitiator'
        personalNumber:
          description: 'The ID number of the user.


            The ID number is a Swedish national identification number (12 digits).'
          example: '200001012384'
          maxLength: 12
          minLength: 12
          pattern: ^[0-9]*$
          type: string
        riskFlags:
          description: 'Indicate to the risk assessment system that the payment has a higher risk or is unusual for the user.

            The riskFlags will not be displayed to the end user.'
          example:
          - largeAmount
          - newCustomer
          - newCard
          items:
            enum:
            - newCard
            - newCustomer
            - newRecipient
            - highRiskRecipient
            - largeAmount
            - foreignCurrency
            - cryptoCurrencyPurchase
            - moneyTransfer
            - overseasTransaction
            - recurringPayment
            - suspiciousPaymentPattern
            - partialNameMatch
            - noNameMatch
            - other
            type: string
          type: array
        userNonVisibleData:
          description: 'Data that you wish to include but not display to the user.


            The value must be base 64-encoded.'
          example: VGV4dCBpbmNsdWRlZCBidXQgbm90IGRpc3BsYXllZCB0byB0aGUgdXNlcg==
          maxLength: 1000
          minLength: 1
          type: string
        userVisibleData:
          description: 'Text displayed to the user during the order.


            The purpose is to provide context, thereby enabling the user to detect identification errors and avert fraud

            attempts.


            The text can be formatted using CR, LF and CRLF for new lines. The text must be encoded as UTF-8 and then base 64

            encoded.'
          example: VGhpcyBpcyBhIHNhbXBsZSB0ZXh0Cg==
          maxLength: 1000
          minLength: 1
          type: string
        userVisibleDataFormat:
          $ref: '#/components/schemas/userVisibleDataFormat'
        userVisibleTransaction:
          $ref: '#/components/schemas/UserVisibleTransaction'
        requirement:
          $ref: '#/components/schemas/phoneSign_request_requirement'
      required:
      - callInitiator
      - personalNumber
      - userVisibleTransaction
      type: object
    limited_response:
      example:
        orderRef: 131daac9-16c6-4618-beb0-365768f37288
      properties:
        orderRef:
          description: 'A reference ID for an order.


            This is used to query the status of the order or to cancel it.'
          example: 131daac9-16c6-4618-beb0-365768f37288
          type: string
      required:
      - orderRef
      type: object
    Direct:
      allOf:
      - $ref: '#/components/schemas/UserVisibleTransactionParentType'
      - properties:
          money:
            $ref: '#/components/schemas/Money'
          recipient:
            $ref: '#/components/schemas/RecipientDirect'
      required:
      - money
      - recipient
      title: direct
      type: object
    RecipientDirect:
      allOf:
      - $ref: '#/components/schemas/RecipientCommon'
      - description: 'Displayed name(s) for the recipient of the direct payment.


          At least one or more of `nameB64`, `legalNameB64`, `account` or `phone` must be specified.'
        properties:
          legalNameB64:
            description: 'The legal name of the direct payment recipient.


              Should be a base64 encoded utf-8 string with a maximum length of 40 unicode code points.'
            maxLength: 215
            minLength: 1
            type: string
          accountNumber:
            description: The account number of the direct payment recipient.
            maxLength: 42
            minLength: 1
            pattern: ^[A-Z0-9.,() -]+$
            type: string
          phoneNumber:
            description: The phone number of the direct payment recipient.
            maxLength: 25
            minLength: 1
            pattern: ^[\d() +-]*$
            type: string
        type: object
      title: recipientDirect
    Money:
      description: Object that sets monetary amount for the payment.<br>If the transactionType is npa this isn't allowed to be set.
      properties:
        amount:
          description: 'The monetary amount of the payment.


            The string can contain one decimal separator which must be `","`. The rest of the input must be numbers.


            Examples: `"1000,00"`, `"100,000"`, `"100"`, `"0"`'
          example: 100,00
          maxLength: 48
          minLength: 1
          type: string
        currency:
          description: 'The currency of the payment.


            This must be an ISO 4217 alphabetic currency code.'
          example: EUR
          maxLength: 3
          minLength: 3
          type: string
      required:
      - amount
      - currency
      title: money
      type: object
    RecipientPlusgiro:
      allOf:
      - $ref: '#/components/schemas/RecipientCommon'
      - properties:
          accountNumber:
            description: The account number of the recipient of the payment.
            maxLength: 42
            minLength: 1
            pattern: ^[A-Z0-9.,() -]+$
            type: string
        type: object
      description: Displayed name and account number for the recipient of the payment.
      required:
      - accountNumber
      title: recipientPlusgiro
    UserVisibleTransactionBulk:
      description: Information about the bulk transaction being approved.
      properties:
        payments:
          description: List of payments to approve.
          items:
            $ref: '#/components/schemas/UserVisibleTransactionBulk_payments_inner'
          maxItems: 40
          minItems: 1
          type: array
        sums:
          description: List of payment sums to approve.
          example:
          - amount: 12,31
            currency: NOK
          - amount: '1200'
            currency: SEK
          - amount: '500'
            currency: USD
          items:
            $ref: '#/components/schemas/Money'
          maxItems: 4
          minItems: 1
          type: array
        thirdPartyInitiatorB64:
          description: 'The third party initiating the payment.


            Should be a base64 encoded utf-8 string with a maximum length of 40 unicode code points.'
          maxLength: 270
          minLength: 1
          type: string
      required:
      - payments
      - sums
      type: object
    Bankgiro:
      allOf:
      - $ref: '#/components/schemas/UserVisibleTransactionParentType'
      - properties:
          money:
            $ref: '#/components/schemas/Money'
          recipient:
            $ref: '#/components/schemas/RecipientBankgiro'
      required:
      - date
      - money
      - recipient
      title: bankgiro
      type: object
    phonePaymentBulk_request:
      properties:
        callInitiator:
          $ref: '#/components/schemas/callInitiator'
        personalNumber:
          description: 'The ID number of the user.


            The ID number is a Swedish national identification number (12 digits).'
          example: '200001012384'
          maxLength: 12
          minLength: 12
          pattern: ^[0-9]*$
          type: string
        userNonVisibleData:
          description: 'Data that you wish to include but not display to the user.


            The value must be base 64-encoded.'
          example: VGV4dCBpbmNsdWRlZCBidXQgbm90IGRpc3BsYXllZCB0byB0aGUgdXNlcg==
          maxLength: 1000
          minLength: 1
          type: string
        userVisibleData:
          description: 'Text displayed to the user during the order.


            The purpose is to provide context, thereby enabling the user to detect identification errors and avert fraud

            attempts.


            The text can be formatted using CR, LF and CRLF for new lines. The text must be encoded as UTF-8 and then base 64

            encoded.'
          example: VGhpcyBpcyBhIHNhbXBsZSB0ZXh0Cg==
          maxLength: 1000
          minLength: 1
          type: string
        userVisibleTransactionBulk:
          $ref: '#/components/schemas/UserVisibleTransactionBulk'
        requirement:
          $ref: '#/components/schemas/phoneSign_request_requirement'
      required:
      - callInitiator
      - personalNumber
      - userVisibleTransactionBulk
      type: object
    RecipientSameBank:
      allOf:
      - $ref: '#/components/schemas/RecipientCommon'
      - properties:
          accountNumber:
            description: The account number of the recipient of the payment.
            maxLength: 42
            minLength: 1
            pattern: ^[A-Z0-9.,() -]+$
            type: string
        type: object
      description: Displayed name and account number for the recipient of the payment.
      required:
      - accountNumber
      title: recipientSameBank
    riskWarning:
      description: "Indicate to the user that the payment has higher risk or is unusual for the user.\nThis will be indicated in the UI.\n\n<table>\n  <thead>\n    <tr>\n      <td>riskWarning</td>\n      <td>text displayed to user</td>\n    </tr>\n  </thead>\n  <tr>\n    <td>newRecipient</td>\n    <td>New recipient</td>\n  </tr>\n  <tr>\n    <td>largeAmount</td>\n    <td>Large amount</td>\n  </tr>\n  <tr>\n    <td>foreignCurrency</td>\n    <td>Foreign currency</td>\n  </tr>\n  <tr>\n    <td>cryptoCurrencyPurchase</td>\n    <td>Purchase of crypto currency</td>\n  </tr>\n  <tr>\n    <td>moneyTransfer</td>\n    <td>Money transfer</td>\n  </tr>\n  <tr>\n    <td>overseasTransaction</td>\n    <td>International payment</td>\n  </tr>\n  <tr>\n    <td>recurringPayment</td>\n    <td>Recurring payment</td>\n  </tr>\n  <tr>\n    <td>partialNameMatch</td>\n    <td>IBAN and name don’t fully match</td>\n  </tr>\n  <tr>\n    <td>noNameMatch</td>\n    <td>IBAN and name don’t match</td>\n  </tr>\n  <tr>\n    <td>other</td>\n    <td>Please verify the details above</td>\n  </tr>\n</table>"
      enum:
      - newRecipient
      - largeAmount
      - foreignCurrency
      - cryptoCurrencyPurchase
      - moneyTransfer
      - overseasTransaction
      - recurringPayment
      - partialNameMatch
      - noNameMatch
      - other
      type: string
    RecipientDomesticBank:
      allOf:
      - $ref: '#/components/schemas/RecipientCommon'
      - properties:
          accountNumber:
            description: The account number of the recipient of the payment.
            maxLength: 42
            minLength: 1
            pattern: ^[A-Z0-9.,() -]+$
            type: string
        type: object
      description: Displayed name and account number for the recipient of the payment.
      required:
      - accountNumber
      title: recipientDomesticBank
    riskFlags:
      description: 'Indicate to the risk assessment system that the payment has a higher risk or is unusual for the user.

        The riskFlags will not be displayed to the end user.'
      example:
      - largeAmount
      - newCustomer
      - newCard
      items:
        enum:
        - newCard
        - newCustomer
        - newRecipient
        - highRiskRecipient
        - largeAmount
        - foreignCurrency
        - cryptoCurrencyPurchase
        - moneyTransfer
        - overseasTransaction
        - recurringPayment
        - suspiciousPaymentPattern
        - partialNameMatch
        - noNameMatch
        - other
        type: string
      type: array
    error_response:
      description: Generic error response
      example:
        errorCode: invalidParameters
        details: Incorrect personalNumber
      properties:
        errorCode:
          description: The error code.
          example: invalidParameters
          type: string
        details:
          description: Additional details specific to the error code.
          example: Incorrect personalNumber
          type: string
      required:
      - details
      - errorCode
      type: object
    phoneSign_request:
      properties:
        callInitiator:
          $ref: '#/components/schemas/callInitiator'
        personalNumber:
          description: 'The ID number of the user.


            The ID number is a Swedish national identification number (12 digits).'
          example: '200001012384'
          maxLength: 12
          minLength: 12
          pattern: ^[0-9]*$
          type: string
        userNonVisibleData:
          description: 'Data that you wish to include but not display to the user.


            The value must be base 64-encoded.'
          example: VGV4dCBpbmNsdWRlZCBidXQgbm90IGRpc3BsYXllZCB0byB0aGUgdXNlcg==
          maxLength: 200000
          minLength: 1
          type: string
        userVisibleData:
          description: 'Text displayed to the user during the order.


            The purpose is to provide context, thereby enabling the user to detect identification errors and avert fraud

            attempts.


            The text can be formatted using CR, LF and CRLF for new lines. The text must be encoded as UTF-8 and then base 64

            encoded.'
          example: VGhpcyBpcyBhIHNhbXBsZSB0ZXh0Cg==
          maxLength: 40000
          minLength: 1
          type: string
        userVisibleDataFormat:
          $ref: '#/components/schemas/userVisibleDataFormat'
        requirement:
          $ref: '#/components/schemas/phoneSign_request_requirement'
      required:
      - callInitiator
      - personalNumber
      - userVisibleData
      type: object
    Card:
      allOf:
      - $ref: '#/components/schemas/UserVisibleTransactionParentType'
      - properties:
          money:
            $ref: '#/components/schemas/Money'
          recipient:
            $ref: '#/components/schemas/RecipientCard'
      required:
      - recipient
      title: card
      type: object
    RecipientCommon:
      properties:
        nameB64:
          description: 'The name of the recipient of the payment.


            For the transaction type `"card"`, this is the merchant name.


            Should be a base64 encoded utf-8 string with a maximum length of 40 unicode code points.'
          maxLength: 215
          minLength: 1
          type: string
      type: object
