openapi: 3.2.0
info:
  description: BankID Relying Party API v6.0
  license:
    name: BankID Privacy policy
    url: https://www.bankid.com/en/integritetspolicy
  title: Relying Party Payment API
  version: 6.1.11
servers:
- description: Test server
  url: https://appapi2.test.bankid.com/rp/v6.0
- description: Production server
  url: https://appapi2.bankid.com/rp/v6.0
tags:
- name: Payment
paths:
  /payment:
    post:
      description: 'Initiates a payment order.


        Use the `/collect` method to query the status of the order.'
      operationId: payment
      requestBody:
        content:
          application/json:
            examples:
              request:
                summary: Example payment request
                value:
                  endUserIp: 192.168.1.2
                  returnUrl: https://bankid.example/auth/login_page#nonce=a3618c72-bc71-4002-b3de-509555b175db
                  returnRisk: true
                  riskFlags:
                  - largeAmount
                  - newCustomer
                  - newCard
                  userVisibleTransaction:
                    transactionType: card
                    recipient:
                      nameB64: UGF5bWVudCBSZWNpcGllbnRzIEluYy4=
                    money:
                      amount: 100,00
                      currency: EUR
                    riskWarning: largeAmount
                  userVisibleData: IFRoaXMgaXMgYSBzYW1wbGUgdGV4dCB0byBiZSBzaWduZWQ=
                  userVisibleDataFormat: simpleMarkdownV1
                  userNonVisibleData: VGV4dCBpbmNsdWRlZCBidXQgbm90IGRpc3BsYXllZCB0byB0aGUgdXNlcg==
              requestSameBank:
                summary: Example payment request (within the same bank)
                value:
                  endUserIp: 192.168.1.2
                  returnUrl: https://bankid.example/auth/login_page#nonce=a3618c72-bc71-4002-b3de-509555b175db
                  returnRisk: true
                  riskFlags:
                  - newCustomer
                  - newCard
                  userVisibleTransaction:
                    transactionType: samebank
                    recipient:
                      nameB64: UGF5bWVudCBSZWNpcGllbnRzIEluYy4=
                      accountNumber: '8862321312'
                    money:
                      amount: 66,22
                      currency: NOK
                    riskWarning: noNameMatch
                    date: 2025-11-10
                  userVisibleData: IFRoaXMgaXMgYSBzYW1wbGUgdGV4dCB0byBiZSBzaWduZWQ=
                  userVisibleDataFormat: simpleMarkdownV1
                  userNonVisibleData: VGV4dCBpbmNsdWRlZCBidXQgbm90IGRpc3BsYXllZCB0byB0aGUgdXNlcg==
              requestDirect:
                summary: Example payment request (direct transaction)
                value:
                  endUserIp: 192.168.1.2
                  returnUrl: https://bankid.example/auth/login_page#nonce=a3618c72-bc71-4002-b3de-509555b175db
                  returnRisk: true
                  riskFlags:
                  - newCustomer
                  - newCard
                  userVisibleTransaction:
                    transactionType: direct
                    recipient:
                      nameB64: UGF5bWVudCBSZWNpcGllbnRzIEluYy4=
                      accountNumber: '8862321312'
                    money:
                      amount: 9900,01
                      currency: USD
                    thirdPartyInitiatorB64: VGhpcmRQYXJ0eSBDb21wYW55
                  userVisibleData: IFRoaXMgaXMgYSBzYW1wbGUgdGV4dCB0byBiZSBzaWduZWQ=
                  userVisibleDataFormat: simpleMarkdownV1
                  userNonVisibleData: VGV4dCBpbmNsdWRlZCBidXQgbm90IGRpc3BsYXllZCB0byB0aGUgdXNlcg==
              stepUp:
                summary: Require the user to perform a step up by either verifying ID document or using facial recognition
                value:
                  endUserIp: 192.168.1.2
                  userVisibleTransaction:
                    transactionType: card
                    recipient:
                      name: Payment Recipients Inc.
                  requirement:
                    stepUp:
                    - mrtd
                    - face
            schema:
              $ref: '#/components/schemas/payment_request'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/order_response'
          description: Request successful.
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_response'
          description: Bad request.
        '401':
          description: You do not have access to the service.
        '403':
          description: You do not have access to the service.
        '404':
          description: An invalid URL path was used.
        '405':
          description: Only HTTP method POST is allowed.
        '408':
          description: Timeout while transmitting the request.
        '415':
          description: The type is missing or invalid.
        '500':
          description: Internal technical error in the BankID system.
        '503':
          description: The service is temporarily unavailable.
      summary: Create a payment order
      tags:
      - Payment
  /payment/bulk:
    post:
      description: 'Initiates a bulk payment order.


        Use the `/collect` method to query the status of the order.'
      operationId: paymentBulk
      requestBody:
        content:
          application/json:
            examples:
              request:
                summary: Example bulk payment request
                value:
                  endUserIp: 192.168.1.2
                  returnUrl: https://bankid.example/auth/login_page#nonce=a3618c72-bc71-4002-b3de-509555b175db
                  returnRisk: true
                  userVisibleTransactionBulk:
                    payments:
                    - transactionType: plusgiro
                      recipient:
                        nameB64: UGF5bWVudCBSZWNpcGllbnRzIEluYy4=
                        accountNumber: 123-4569
                      money:
                        amount: 100,00
                        currency: SEK
                      riskWarning: largeAmount
                      date: 2025-11-10
                    - transactionType: bankgiro
                      recipient:
                        nameB64: UGF5bWVudCBSZWNpcGllbnRzIEJhbmtnaXJvIEluYy4=
                        accountNumber: 1234-1234
                      fromAccount:
                        accountNumber: '12312313'
                      money:
                        amount: 100,00
                        currency: SEK
                      riskWarning: largeAmount
                      date: 2025-11-10
                      riskFlags:
                      - largeAmount
                      - newCustomer
                      - newCard
                    sums:
                    - amount: 200,00
                      currency: SEK
                    thirdPartyInitiatorB64: VGhpcmRQYXJ0eSBDb21wYW55
                  userVisibleData: IFRoaXMgaXMgYSBzYW1wbGUgdGV4dCB0byBiZSBzaWduZWQ=
                  userNonVisibleData: VGV4dCBpbmNsdWRlZCBidXQgbm90IGRpc3BsYXllZCB0byB0aGUgdXNlcg==
            schema:
              $ref: '#/components/schemas/paymentBulk_request'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/order_response'
          description: Request successful.
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_response'
          description: Bad request.
        '401':
          description: You do not have access to the service.
        '403':
          description: You do not have access to the service.
        '404':
          description: An invalid URL path was used.
        '405':
          description: Only HTTP method POST is allowed.
        '408':
          description: Timeout while transmitting the request.
        '415':
          description: The type is missing or invalid.
        '500':
          description: Internal technical error in the BankID system.
        '503':
          description: The service is temporarily unavailable.
      summary: Create a bulk payment order
      tags:
      - Payment
components:
  schemas:
    RecipientCard:
      allOf:
      - $ref: '#/components/schemas/RecipientCommon'
      - properties:
          name:
            description: 'The name of the recipient of the payment.


              For the transaction type `"card"`, this is the merchant name.

              This property is here for backwards compatibility only.

              The preferred way of declaring the name of the recipient is to use nameB64 instead.'
            maxLength: 40
            type: string
        type: object
      description: 'Displayed name for the recipient of the payment.

        Exactly one of `name` and `nameB64` must be populated.'
      title: recipientCard
    UserVisibleTransactionParentType:
      properties:
        transactionType:
          description: 'The type of transaction.


            The possible values have the following meaning:


            - `card`: Card payment.

            - `npa`: Non-payment authentication.

            - `bankgiro`: Bankgiro payment.

            - `plusgiro`: Plusgiro payment.

            - `samebank`: Same bank transfer.

            - `domesticbank`: Domestic bank transfer.

            - `foreignbank`: Foreign bank transfer.

            - `direct`: Direct payment.'
          enum:
          - card
          - npa
          - bankgiro
          - plusgiro
          - samebank
          - domesticbank
          - foreignbank
          - direct
          type: string
        date:
          description: 'The date for the payment to occur.


            Should be a formatted as YYYY-MM-DD.'
          format: date
          type: string
        riskWarning:
          $ref: '#/components/schemas/riskWarning'
        recurring:
          default: false
          description: Indicate to the user if the payment is a recurring one or not.
          type: boolean
        thirdPartyInitiatorB64:
          description: 'The third party initiating the payment.


            Should be a base64 encoded utf-8 string with a maximum length of 40 unicode code points.'
          maxLength: 270
          minLength: 1
          type: string
      type: object
    cardReader:
      description: "Whether the user needs to complete the order using a card reader for the signature.\n\nThe possible values have the following meaning:\n\n  *  `class1`: The order must be confirmed with a card reader where the PIN code is entered on a computer keyboard,\n     or a card reader of higher class.\n  *  `class2`: The order must be confirmed with a card reader where the PIN code is entered on the reader.\n\nThis condition should always be combined with a `certificatePolicies` for a smart card to avoid undefined\nbehaviour.\n\nNo card reader is required by default."
      enum:
      - class1
      - class2
      type: string
    Npa:
      allOf:
      - $ref: '#/components/schemas/UserVisibleTransactionParentType'
      - properties:
          recipient:
            $ref: '#/components/schemas/RecipientNpa'
      required:
      - recipient
      title: npa
      type: object
    RecipientNpa:
      allOf:
      - $ref: '#/components/schemas/RecipientCommon'
      - properties:
          name:
            description: 'The name of the recipient of the payment.

              This property is here for backwards compatibility only.

              The preferred way of declaring the name of the recipient is to use nameB64 instead.'
            maxLength: 40
            type: string
        type: object
      description: 'Displayed name for the recipient of the payment.

        Exactly one of `name` and `nameB64` must be populated.'
      title: recipientNpa
    userVisibleDataFormat:
      description: "If present and set to `\"simpleMarkdownV1\"`, this parameter indicates that `userVisibleData` holds formatting\ncharacters.\n\nThe possible values have the following meaning:\n\n-  `plaintext`: `userVisibleData` contains base 64 encoded text using a sub-set of UTF-8 and CR, LF or CRLF for\n   line breaks..\n-  `simpleMarkdownV1`: `userVisibleData` contains Simple Markdown version 1.\n\nPlease see\n[the documentation](https://developers.bankid.com/getting-started/backend/formatting-text/syntax-special-characters-and-rendering)\nfor more information about the format."
      enum:
      - plaintext
      - simpleMarkdownV1
      type: string
    payment_request_requirement:
      description: Requirements on how the payment order must be performed.
      properties:
        cardReader:
          $ref: '#/components/schemas/cardReader'
        certificatePolicies:
          description: 'The OID in certificate policies in the user certificate.


            One wildcard is allowed from position 5 and forward (`"1.2.752.78.*"`).


            Available values for production BankIDs are:

            *  `"1.2.752.78.1.1"` - BankID on file

            *  `"1.2.752.78.1.2"` - BankID on card

            *  `"1.2.752.78.1.5"` - Mobile BankID


            Available values for test BankIDs are:

            *  `"1.2.3.4.5"` - BankID on file

            *  `"1.2.3.4.10"` - BankID on card

            *  `"1.2.3.4.25"` - Mobile BankID

            *  `"1.2.752.60.1.6"` - Test BankID for some BankID banks


            When using one of the _BankID on card_ policies, the `cardReader` requirement can be used to further restrict the

            type of card reader allowed. If no `cardReader` requirement is passed, all supported kinds of card readers are

            permitted.'
          example:
          - 1.2.752.78.1.1
          items:
            type: string
          type: array
        pinCode:
          description: Users are required to confirm the order with their security code even if they have biometrics activated.
          example: false
          type: boolean
        mrtd:
          description: 'Whether the user needs to confirm their identity with a valid Swedish passport or national ID card to complete the

            order.


            No identity confirmation is required by default.'
          type: boolean
        personalNumber:
          description: 'The personal identity number allowed to confirm the identification.


            If a BankID with another personal identity number attempts to confirm the identification, it will fail.'
          example: '200001012384'
          maxLength: 12
          minLength: 12
          pattern: ^[0-9]*$
          type: string
        stepUp:
          description: 'Whether the user needs to perform a step up.


            The possible values have the following meaning:

            - `mrtd`: Confirm identity with a valid Swedish passport or national ID card to complete the order.

            - `face`: Confirm identity with facial recognition.


            Use multiple values to let the user choose between the available identity confirmations.


            The `requirement.stepUp` property can not be used in combination with the property `requirement.mrtd`.


            Requesting identity confirmation with facial recognition as the only option is not supported.


            No identity confirmation is required by default.'
          items:
            type: string
          type: array
      type: object
    ForeignBank:
      allOf:
      - $ref: '#/components/schemas/UserVisibleTransactionParentType'
      - properties:
          money:
            $ref: '#/components/schemas/Money'
          recipient:
            $ref: '#/components/schemas/RecipientForeignBank'
      required:
      - date
      - money
      - recipient
      title: foreignbank
      type: object
    RecipientForeignBank:
      allOf:
      - $ref: '#/components/schemas/RecipientCommon'
      - properties:
          accountNumber:
            description: The account number of the recipient of the payment.
            maxLength: 42
            minLength: 1
            pattern: ^[A-Z0-9.,() -]+$
            type: string
        type: object
      description: Displayed name and account number for the recipient of the payment.
      required:
      - accountNumber
      title: recipientForeignBank
    SameBank:
      allOf:
      - $ref: '#/components/schemas/UserVisibleTransactionParentType'
      - properties:
          money:
            $ref: '#/components/schemas/Money'
          recipient:
            $ref: '#/components/schemas/RecipientSameBank'
      required:
      - date
      - money
      - recipient
      title: samebank
      type: object
    DomesticBank:
      allOf:
      - $ref: '#/components/schemas/UserVisibleTransactionParentType'
      - properties:
          money:
            $ref: '#/components/schemas/Money'
          recipient:
            $ref: '#/components/schemas/RecipientDomesticBank'
      required:
      - date
      - money
      - recipient
      title: domesticbank
      type: object
    Plusgiro:
      allOf:
      - $ref: '#/components/schemas/UserVisibleTransactionParentType'
      - properties:
          money:
            $ref: '#/components/schemas/Money'
          recipient:
            $ref: '#/components/schemas/RecipientPlusgiro'
      required:
      - date
      - money
      - recipient
      title: plusgiro
      type: object
    paymentBulk_request:
      properties:
        app:
          $ref: '#/components/schemas/app'
        endUserIp:
          description: 'The user IP address as it is seen by your service.


            IPv4 and IPv6 are allowed.


            Make sure that the IP address you include as `endUserIp` is the address of your end user''s device, not the internal

            address of any reverse proxy between you and the end user.


            In use cases where the IP address is not available, e. g. for voice-based services, the internal representation of

            those systems'' IP address is ok to use.'
          example: 192.168.1.2
          type: string
        returnRisk:
          description: 'If this is set to `true` a risk indicator will be included in the collect response when the order completes.

            The risk indication requires that the endUserIp is correct.'
          example: true
          type: boolean
        returnUrl:
          description: 'Orders started on the same device as where the user''s BankID is stored (started with autostart token) will call

            this URL when the order is completed.


            Any return URL provided in the start URL when the BankID app was launched will be ignored. If the user has a

            version of the BankID app that does not support getting the `returnUrl` from the server, the order will be

            cancelled and the user will be asked to update their app.


            The return URL you provide should include a nonce to the session. When the user returns to your app or web page,

            your service should verify that the order was completed successfully and that the device receiving the

            `returnUrl` is the same device that started the order.


            Using this parameter will make your service more secure and strengthen the channel binding between you and the

            user.


            Ensure that the cookie or user IP address has not changed from the starting page to the `returnUrl` page.'
          example: https://bankid.example/auth/login_page#nonce=a3618c72-bc71-4002-b3de-509555b175db
          maxLength: 512
          minLength: 1
          type: string
        userNonVisibleData:
          description: 'Data that you wish to include but not display to the user.


            The value must be base 64-encoded.'
          example: VGV4dCBpbmNsdWRlZCBidXQgbm90IGRpc3BsYXllZCB0byB0aGUgdXNlcg==
          maxLength: 1000
          minLength: 1
          type: string
        userVisibleData:
          description: 'Text displayed to the user during the order.


            The purpose is to provide context, thereby enabling the user to detect identification errors and avert fraud

            attempts.


            The text can be formatted using CR, LF and CRLF for new lines. The text must be encoded as UTF-8 and then base 64

            encoded.'
          example: VGhpcyBpcyBhIHNhbXBsZSB0ZXh0Cg==
          maxLength: 1000
          minLength: 1
          type: string
        userVisibleTransactionBulk:
          $ref: '#/components/schemas/UserVisibleTransactionBulk'
        web:
          $ref: '#/components/schemas/web'
        requirement:
          $ref: '#/components/schemas/payment_request_requirement'
      required:
      - endUserIp
      - userVisibleTransactionBulk
      type: object
    UserVisibleTransaction:
      description: Information about the transaction being approved.
      discriminator:
        mapping:
          card: '#/components/schemas/Card'
          npa: '#/components/schemas/Npa'
          bankgiro: '#/components/schemas/Bankgiro'
          plusgiro: '#/components/schemas/Plusgiro'
          samebank: '#/components/schemas/SameBank'
          domesticbank: '#/components/schemas/DomesticBank'
          foreignbank: '#/components/schemas/ForeignBank'
          direct: '#/components/schemas/Direct'
        propertyName: transactionType
      oneOf:
      - $ref: '#/components/schemas/Card'
      - $ref: '#/components/schemas/Npa'
      - $ref: '#/components/schemas/Bankgiro'
      - $ref: '#/components/schemas/Plusgiro'
      - $ref: '#/components/schemas/SameBank'
      - $ref: '#/components/schemas/DomesticBank'
      - $ref: '#/components/schemas/ForeignBank'
      - $ref: '#/components/schemas/Direct'
      required:
      - transactionType
      type: object
    UserVisibleTransactionBulk_payments_inner_allOf_fromAccount:
      description: "The account the payment is taken from.\n\nItems adjacent to each other in `payments` will be grouped together if share the same `fromAccount` values.  \n\nEither `nameB64` or `accountNumber` is required."
      properties:
        nameB64:
          description: 'The name of the account.


            Should be a base64 encoded utf-8 string with a maximum length of 40 unicode code points.'
          maxLength: 215
          minLength: 1
          type: string
        accountNumber:
          description: The account number the transfer is sourced from.
          format: string
          maxLength: 42
          minLength: 1
          pattern: ^[A-Z0-9.,() -]+$
          type: string
      type: object
    app:
      description: 'Additional data included when creating an order from your app.


        When starting an order from your app client this data may be included in the request.


        You can send the parameter `web` or `app`, not both. If providing this parameter, at least one of its members must

        be specified.'
      properties:
        appIdentifier:
          description: 'The identifier of your application.


            This is the package name on Android and the bundle identifier on iOS.


            It is vital to use the correct value. If your service does not supply the correct value legitimate orders might

            be blocked.'
          example: se.demobank.app1
          maxLength: 256
          minLength: 2
          type: string
        deviceOS:
          description: The device operating system where your app is running.
          example: ANDROID 14.0
          maxLength: 128
          minLength: 1
          type: string
        deviceIdentifier:
          description: 'The identifier of the device your client is running on.


            This is used to uniquely identify the device and should be a value that is not tied to a single user of the

            device. Preferably, it should remain the same even if your app is reinstalled.'
          example: e753b91e-9c84-4441-aadb-0832f4c71fac
          maxLength: 64
          minLength: 1
          type: string
        deviceModelName:
          description: The model of the device your app is running on.
          example: Apple iPhone14,3
          maxLength: 128
          minLength: 1
          type: string
      type: object
    TransactionBulk:
      properties:
        transactionType:
          description: 'The type of transaction.


            The possible values have the following meaning:


            - `bankgiro`: Bankgiro payment.

            - `plusgiro`: Plusgiro payment.

            - `samebank`: Same bank transfer.

            - `domesticbank`: Domestic bank transfer.

            - `foreignbank`: Foreign bank transfer.'
          enum:
          - bankgiro
          - plusgiro
          - samebank
          - domesticbank
          - foreignbank
          type: string
        date:
          description: 'The date for the payment to occur.


            Should be a formatted as YYYY-MM-DD.'
          format: date
          type: string
        riskWarning:
          $ref: '#/components/schemas/riskWarning'
      required:
      - date
      - money
      - transactionType
      type: object
    RecipientGenericBulk:
      allOf:
      - $ref: '#/components/schemas/RecipientCommon'
      - properties:
          accountNumber:
            description: The account number of the recipient of the payment.
            maxLength: 42
            minLength: 1
            pattern: ^[A-Z0-9.,() -]+$
            type: string
        type: object
      description: Displayed name and account number for the recipient of the payment.
      required:
      - accountNumber
    UserVisibleTransactionBulk_payments_inner:
      allOf:
      - $ref: '#/components/schemas/TransactionBulk'
      - properties:
          money:
            $ref: '#/components/schemas/Money'
          recipient:
            $ref: '#/components/schemas/RecipientGenericBulk'
          fromAccount:
            $ref: '#/components/schemas/UserVisibleTransactionBulk_payments_inner_allOf_fromAccount'
          riskFlags:
            $ref: '#/components/schemas/riskFlags'
      required:
      - recipient
    RecipientBankgiro:
      allOf:
      - $ref: '#/components/schemas/RecipientCommon'
      - properties:
          accountNumber:
            description: The account number of the recipient of the payment.
            maxLength: 42
            minLength: 1
            pattern: ^[A-Z0-9.,() -]+$
            type: string
        type: object
      description: Displayed name and account number for the recipient of the payment.
      required:
      - accountNumber
      title: recipientBankgiro
    Direct:
      allOf:
      - $ref: '#/components/schemas/UserVisibleTransactionParentType'
      - properties:
          money:
            $ref: '#/components/schemas/Money'
          recipient:
            $ref: '#/components/schemas/RecipientDirect'
      required:
      - money
      - recipient
      title: direct
      type: object
    RecipientDirect:
      allOf:
      - $ref: '#/components/schemas/RecipientCommon'
      - description: 'Displayed name(s) for the recipient of the direct payment.


          At least one or more of `nameB64`, `legalNameB64`, `account` or `phone` must be specified.'
        properties:
          legalNameB64:
            description: 'The legal name of the direct payment recipient.


              Should be a base64 encoded utf-8 string with a maximum length of 40 unicode code points.'
            maxLength: 215
            minLength: 1
            type: string
          accountNumber:
            description: The account number of the direct payment recipient.
            maxLength: 42
            minLength: 1
            pattern: ^[A-Z0-9.,() -]+$
            type: string
          phoneNumber:
            description: The phone number of the direct payment recipient.
            maxLength: 25
            minLength: 1
            pattern: ^[\d() +-]*$
            type: string
        type: object
      title: recipientDirect
    Money:
      description: Object that sets monetary amount for the payment.<br>If the transactionType is npa this isn't allowed to be set.
      properties:
        amount:
          description: 'The monetary amount of the payment.


            The string can contain one decimal separator which must be `","`. The rest of the input must be numbers.


            Examples: `"1000,00"`, `"100,000"`, `"100"`, `"0"`'
          example: 100,00
          maxLength: 48
          minLength: 1
          type: string
        currency:
          description: 'The currency of the payment.


            This must be an ISO 4217 alphabetic currency code.'
          example: EUR
          maxLength: 3
          minLength: 3
          type: string
      required:
      - amount
      - currency
      title: money
      type: object
    RecipientPlusgiro:
      allOf:
      - $ref: '#/components/schemas/RecipientCommon'
      - properties:
          accountNumber:
            description: The account number of the recipient of the payment.
            maxLength: 42
            minLength: 1
            pattern: ^[A-Z0-9.,() -]+$
            type: string
        type: object
      description: Displayed name and account number for the recipient of the payment.
      required:
      - accountNumber
      title: recipientPlusgiro
    UserVisibleTransactionBulk:
      description: Information about the bulk transaction being approved.
      properties:
        payments:
          description: List of payments to approve.
          items:
            $ref: '#/components/schemas/UserVisibleTransactionBulk_payments_inner'
          maxItems: 40
          minItems: 1
          type: array
        sums:
          description: List of payment sums to approve.
          example:
          - amount: 12,31
            currency: NOK
          - amount: '1200'
            currency: SEK
          - amount: '500'
            currency: USD
          items:
            $ref: '#/components/schemas/Money'
          maxItems: 4
          minItems: 1
          type: array
        thirdPartyInitiatorB64:
          description: 'The third party initiating the payment.


            Should be a base64 encoded utf-8 string with a maximum length of 40 unicode code points.'
          maxLength: 270
          minLength: 1
          type: string
      required:
      - payments
      - sums
      type: object
    Bankgiro:
      allOf:
      - $ref: '#/components/schemas/UserVisibleTransactionParentType'
      - properties:
          money:
            $ref: '#/components/schemas/Money'
          recipient:
            $ref: '#/components/schemas/RecipientBankgiro'
      required:
      - date
      - money
      - recipient
      title: bankgiro
      type: object
    RecipientSameBank:
      allOf:
      - $ref: '#/components/schemas/RecipientCommon'
      - properties:
          accountNumber:
            description: The account number of the recipient of the payment.
            maxLength: 42
            minLength: 1
            pattern: ^[A-Z0-9.,() -]+$
            type: string
        type: object
      description: Displayed name and account number for the recipient of the payment.
      required:
      - accountNumber
      title: recipientSameBank
    riskWarning:
      description: "Indicate to the user that the payment has higher risk or is unusual for the user.\nThis will be indicated in the UI.\n\n<table>\n  <thead>\n    <tr>\n      <td>riskWarning</td>\n      <td>text displayed to user</td>\n    </tr>\n  </thead>\n  <tr>\n    <td>newRecipient</td>\n    <td>New recipient</td>\n  </tr>\n  <tr>\n    <td>largeAmount</td>\n    <td>Large amount</td>\n  </tr>\n  <tr>\n    <td>foreignCurrency</td>\n    <td>Foreign currency</td>\n  </tr>\n  <tr>\n    <td>cryptoCurrencyPurchase</td>\n    <td>Purchase of crypto currency</td>\n  </tr>\n  <tr>\n    <td>moneyTransfer</td>\n    <td>Money transfer</td>\n  </tr>\n  <tr>\n    <td>overseasTransaction</td>\n    <td>International payment</td>\n  </tr>\n  <tr>\n    <td>recurringPayment</td>\n    <td>Recurring payment</td>\n  </tr>\n  <tr>\n    <td>partialNameMatch</td>\n    <td>IBAN and name don’t fully match</td>\n  </tr>\n  <tr>\n    <td>noNameMatch</td>\n    <td>IBAN and name don’t match</td>\n  </tr>\n  <tr>\n    <td>other</td>\n    <td>Please verify the details above</td>\n  </tr>\n</table>"
      enum:
      - newRecipient
      - largeAmount
      - foreignCurrency
      - cryptoCurrencyPurchase
      - moneyTransfer
      - overseasTransaction
      - recurringPayment
      - partialNameMatch
      - noNameMatch
      - other
      type: string
    RecipientDomesticBank:
      allOf:
      - $ref: '#/components/schemas/RecipientCommon'
      - properties:
          accountNumber:
            description: The account number of the recipient of the payment.
            maxLength: 42
            minLength: 1
            pattern: ^[A-Z0-9.,() -]+$
            type: string
        type: object
      description: Displayed name and account number for the recipient of the payment.
      required:
      - accountNumber
      title: recipientDomesticBank
    riskFlags:
      description: 'Indicate to the risk assessment system that the payment has a higher risk or is unusual for the user.

        The riskFlags will not be displayed to the end user.'
      example:
      - largeAmount
      - newCustomer
      - newCard
      items:
        enum:
        - newCard
        - newCustomer
        - newRecipient
        - highRiskRecipient
        - largeAmount
        - foreignCurrency
        - cryptoCurrencyPurchase
        - moneyTransfer
        - overseasTransaction
        - recurringPayment
        - suspiciousPaymentPattern
        - partialNameMatch
        - noNameMatch
        - other
        type: string
      type: array
    error_response:
      description: Generic error response
      example:
        errorCode: invalidParameters
        details: Incorrect personalNumber
      properties:
        errorCode:
          description: The error code.
          example: invalidParameters
          type: string
        details:
          description: Additional details specific to the error code.
          example: Incorrect personalNumber
          type: string
      required:
      - details
      - errorCode
      type: object
    payment_request:
      properties:
        app:
          $ref: '#/components/schemas/app'
        endUserIp:
          description: 'The user IP address as it is seen by your service.


            IPv4 and IPv6 are allowed.


            Make sure that the IP address you include as `endUserIp` is the address of your end user''s device, not the internal

            address of any reverse proxy between you and the end user.


            In use cases where the IP address is not available, e. g. for voice-based services, the internal representation of

            those systems'' IP address is ok to use.'
          example: 192.168.1.2
          type: string
        returnRisk:
          description: 'If this is set to `true` a risk indicator will be included in the collect response when the order completes.

            The risk indication requires that the endUserIp is correct.'
          example: true
          type: boolean
        returnUrl:
          description: 'Orders started on the same device as where the user''s BankID is stored (started with autostart token) will call

            this URL when the order is completed.


            Any return URL provided in the start URL when the BankID app was launched will be ignored. If the user has a

            version of the BankID app that does not support getting the `returnUrl` from the server, the order will be

            cancelled and the user will be asked to update their app.


            The return URL you provide should include a nonce to the session. When the user returns to your app or web page,

            your service should verify that the order was completed successfully and that the device receiving the

            `returnUrl` is the same device that started the order.


            Using this parameter will make your service more secure and strengthen the channel binding between you and the

            user.


            Ensure that the cookie or user IP address has not changed from the starting page to the `returnUrl` page.'
          example: https://bankid.example/auth/login_page#nonce=a3618c72-bc71-4002-b3de-509555b175db
          maxLength: 512
          minLength: 1
          type: string
        riskFlags:
          description: 'Indicate to the risk assessment system that the payment has a higher risk or is unusual for the user.

            The riskFlags will not be displayed to the end user.'
          example:
          - largeAmount
          - newCustomer
          - newCard
          items:
            enum:
            - newCard
            - newCustomer
            - newRecipient
            - highRiskRecipient
            - largeAmount
            - foreignCurrency
            - cryptoCurrencyPurchase
            - moneyTransfer
            - overseasTransaction
            - recurringPayment
            - suspiciousPaymentPattern
            - partialNameMatch
            - noNameMatch
            - other
            type: string
          type: array
        userNonVisibleData:
          description: 'Data that you wish to include but not display to the user.


            The value must be base 64-encoded.'
          example: VGV4dCBpbmNsdWRlZCBidXQgbm90IGRpc3BsYXllZCB0byB0aGUgdXNlcg==
          maxLength: 1000
          minLength: 1
          type: string
        userVisibleData:
          description: 'Text displayed to the user during the order.


            The purpose is to provide context, thereby enabling the user to detect identification errors and avert fraud

            attempts.


            The text can be formatted using CR, LF and CRLF for new lines. The text must be encoded as UTF-8 and then base 64

            encoded.'
          example: VGhpcyBpcyBhIHNhbXBsZSB0ZXh0Cg==
          maxLength: 1000
          minLength: 1
          type: string
        userVisibleDataFormat:
          $ref: '#/components/schemas/userVisibleDataFormat'
        userVisibleTransaction:
          $ref: '#/components/schemas/UserVisibleTransaction'
        web:
          $ref: '#/components/schemas/web'
        requirement:
          $ref: '#/components/schemas/payment_request_requirement'
      required:
      - endUserIp
      - userVisibleTransaction
      type: object
    web:
      description: 'Additional data included when creating an order from your web page.


        When starting an order from your web page this data may be included in the request.


        You can send the parameter `web` or `app`, not both. If providing this parameter, at least one of its members must

        be specified.'
      properties:
        deviceIdentifier:
          description: 'The identifier of the device running your client.


            Do not use a session cookie. Use a separate cookie or the hash of one.


            This value should be unique to the user''s browser and persist across sessions.'
          example: e753b91e-9c84-4441-aadb-0832f4c71fac
          maxLength: 64
          minLength: 1
          type: string
        referringDomain:
          description: 'The domain that starts the BankID app.


            This should generally be your domain name followed by the public suffix, which will generally be the top level

            domain.


            Only the digits 0 to 9, the letters a to z, dot (".") and dash ("-") are allowed. When using an International

            Domain Name, the string must be punycode encoded.'
          example: example.com
          maxLength: 253
          minLength: 3
          pattern: '[0-9a-z-.]*'
          type: string
        userAgent:
          description: The user agent of the user interacting with your web page.
          example: Mozilla/5.0 (iPhone; CPU iPhone OS 17_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.4.1 Mobile/15E148 Safari/604.1
          maxLength: 512
          minLength: 1
          type: string
      type: object
    order_response:
      example:
        orderRef: 131daac9-16c6-4618-beb0-365768f37288
        autoStartToken: 7c40b5c9-fa74-49cf-b98c-bfe651f9a7c6
        qrStartToken: 67df3917-fa0d-44e5-b327-edcc928297f8
        qrStartSecret: d28db9a7-4cde-429e-a983-359be676944c
      properties:
        orderRef:
          description: 'A reference ID for an order.


            This is used to query the status of the order or to cancel it.'
          example: 131daac9-16c6-4618-beb0-365768f37288
          type: string
        autoStartToken:
          description: Used to compile the start URL.
          example: 7c40b5c9-fa74-49cf-b98c-bfe651f9a7c6
          type: string
        qrStartToken:
          description: Used to compute the animated QR code.
          example: 67df3917-fa0d-44e5-b327-edcc928297f8
          type: string
        qrStartSecret:
          description: Used to compute the animated QR code.
          example: d28db9a7-4cde-429e-a983-359be676944c
          type: string
      required:
      - autoStartToken
      - orderRef
      - qrStartSecret
      - qrStartToken
      type: object
    Card:
      allOf:
      - $ref: '#/components/schemas/UserVisibleTransactionParentType'
      - properties:
          money:
            $ref: '#/components/schemas/Money'
          recipient:
            $ref: '#/components/schemas/RecipientCard'
      required:
      - recipient
      title: card
      type: object
    RecipientCommon:
      properties:
        nameB64:
          description: 'The name of the recipient of the payment.


            For the transaction type `"card"`, this is the merchant name.


            Should be a base64 encoded utf-8 string with a maximum length of 40 unicode code points.'
          maxLength: 215
          minLength: 1
          type: string
      type: object
